from models import SmokeTest

SMOKE_TESTS: list[SmokeTest] = [
    SmokeTest(
        id="SMK-001",
        name="Health check",
        endpoint="/api/health",
        method="GET",
        expected_status=200,
        criticality="critical",
        tags=["smoke", "health"],
    ),
    SmokeTest(
        id="SMK-002",
        name="Login endpoint",
        endpoint="/api/auth/login",
        method="POST",
        expected_status=200,
        criticality="critical",
        tags=["smoke", "auth"],
        payload={"email": "test@smokecrm.dev", "password": "test123"},
    ),
    SmokeTest(
        id="SMK-003",
        name="Get current user",
        endpoint="/api/users/me",
        method="GET",
        expected_status=200,
        criticality="critical",
        tags=["smoke", "auth"],
    ),
    SmokeTest(
        id="SMK-004",
        name="List products",
        endpoint="/api/products",
        method="GET",
        expected_status=200,
        criticality="high",
        tags=["smoke", "catalog"],
    ),
    SmokeTest(
        id="SMK-005",
        name="List orders",
        endpoint="/api/orders",
        method="GET",
        expected_status=200,
        criticality="high",
        tags=["smoke", "orders"],
    ),
    SmokeTest(
        id="SMK-006",
        name="Create order",
        endpoint="/api/orders",
        method="POST",
        expected_status=201,
        criticality="critical",
        tags=["smoke", "orders"],
        payload={"product_id": "prod_001", "quantity": 1},
    ),
    SmokeTest(
        id="SMK-007",
        name="Search products",
        endpoint="/api/products/search",
        method="GET",
        expected_status=200,
        criticality="medium",
        tags=["smoke", "catalog"],
    ),
    SmokeTest(
        id="SMK-008",
        name="Notifications",
        endpoint="/api/notifications",
        method="GET",
        expected_status=200,
        criticality="low",
        tags=["smoke"],
    ),
]
